### ISSUE TITLE
How to pass argument?

### ISSUE THREAD

**Issue by majg0** [JoshMcguigan/cargo-run-script#1]
Something like

`cargo run-script test footest` where `footest` is a specific test I want to focus on
`footest = "cargo test $1"`

not saying exactly like this but you get the point.

Can it be done today? If not, are you able to add it?

**Comment by JoshMcguigan** [comment]
That feature is not supported. It is a good idea, but something I never got around to adding, and I don't use this crate myself anymore. If you'd like to submit a PR adding this I'd be happy to accept, otherwise I'd suggest looking at alternatives.

**Comment by majg0** [comment]
Thanks!

What do you personally use instead?

**Comment by JoshMcguigan** [comment]
In most cases I'll create either a Makefile or just one or more bash scripts.
